Use pnpm to Replace Yarn
hackclub/site pull request #1082
Opened 2024-02-22 08:24 UTC by TakumiBC

`pnpm` has a better efficiency compared to `yarn`. It will increase the speed of our package management, and also speed up builds.
I have also created a `.eslintignore` file to let `ESLint` ignore files like `README.md`.

2024-02-22 08:36 UTC, maxwofford commented
Hey @TakumiBC, thanks for the interest in maintaining the repo!

We use yarn because we've tried pnpm before in other repos and run into issues on virtual and syncing filesystems like dropbox. Considering our builds don't take that long to spin up in production and run fine on an m1 macbook when running `yarn dev`, I don't think we're looking to change package managers currently.

2024-02-23 00:47 UTC, aramshiva commented
Fixes #1042

2024-02-24 04:06 UTC, maxwofford commented
I'll move the discussion there!

2024-04-02 21:01 UTC, grymmy requested changes
Please fix conflicts and re-ping me.

2024-04-03 14:31 UTC, TakumiBC commented
@grymmy Fixed the conflicts. Please help me approve the Vercel build.

2024-04-03 15:30 UTC, grymmy commented
Can you please provide the actual build speed gains realized from this change?  How much faster is it with this change?

2025-04-17 23:40 UTC, closed without merging