Sprig Gallery API
hackclub/site pull request #1129
Opened 2024-03-20 16:50 UTC by GalaxyGamingBoy

2024-03-20 16:51 UTC, GalaxyGamingBoy commented
cc @JosiasAurel @grymmy (I don't have perms to add yall to reviewers so i'll just cc)

2024-03-25 17:33 UTC, JosiasAurel requested changes
lgtm. please remove the gitpod config file

2024-03-25 17:33 UTC, JosiasAurel commented on .gitpod.yml
please remove this gitpod config file

2024-03-27 06:43 UTC, JosiasAurel requested changes

2024-03-27 06:43 UTC, JosiasAurel commented on pages/api/games.js
> +  games.length = 4
let's make it clear this is supposed to return just the first 4 games. use a .slice

2024-03-27 06:44 UTC, JosiasAurel commented on pages/api/games.js
> +  games.length = 4
or add a comment explaining what this does

2024-03-29 18:06 UTC, JosiasAurel approved these changes

2024-04-01 15:15 UTC, grymmy approved these changes

2024-04-10 14:03 UTC, merged