Patch 5
hackclub/site pull request #1282
Opened 2024-07-18 20:57 UTC by sahitid

2024-08-25 21:45 UTC, sampoder requested changes
Can we grab a photo for Apocalypse?

2024-08-26 10:58 UTC, cytronicoder commented on pages/events.js
> +    logo: '',
you can put https://cloud-okxvflzju-hack-club-bot.vercel.app/1summit2.png for the summit logo!

https://cloud-okxvflzju-hack-club-bot.vercel.app/0summit1.png or https://cloud-okxvflzju-hack-club-bot.vercel.app/2summit3.png also works I think; I just took the favicon

2024-08-26 10:58 UTC, cytronicoder reviewed
just adding to the meta info!

2026-02-07 23:53 UTC, 3kh0 requested changes
Image links broken + Events over

2026-02-07 23:53 UTC, closed without merging