feat: Add cider to the top
hackclub/site pull request #1390
Opened 2024-09-25 15:28 UTC by faisalsayed10

I believe Cider is the most relevant of all ysws for Congressional App Challenge, so we should put it somewhere people can see it easily

2024-09-25 15:30 UTC, lachlanjc commented
#### 📝 Changed routes:


| [**…essional-app-challenge**](https://site-oo91mg5r3.hackclub.dev/congressional-app-challenge) |
|:-:|
|<a href="https://site-oo91mg5r3.hackclub.dev/congressional-app-challenge"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/tJFZiI35PSGH6KMlDmiwP7A4cba1GYh69PKqzC0NGvdurXtkXV7AQc4HArEuwrcq__6QEZvBAqsQrn7UuiyQ_Q.png&w=600" alt="Screenshot of /congressional-app-challenge" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/RQuqNv9N_JZcno6sTlLjNou2MEHcpBkxF5MtzsdfsTddhJV_BqwLJz8QldVcHGCnZfZIRc5Ys8Q9Yb_kLj3p2w.png">(view full size)</a> |







Commit 5084cca17c379d835793a276fd82185e472bfaec (https://site-oo91mg5r3.hackclub.dev).

2024-09-25 15:36 UTC, recursiveforte approved these changes

2024-09-25 15:38 UTC, grymmy requested changes
plz put cider at bottom of list

2024-09-26 15:06 UTC, grymmy approved these changes

2024-09-26 15:17 UTC, merged