add language on what hack club is :)
hackclub/site pull request #637
Opened 2022-12-17 21:31 UTC by bellesea

2022-12-17 21:32 UTC, lachlanjc commented
#### 📝 Changed routes:


| [**/winter**](https://site-7q12wp5fs.hackclub.dev/winter) |
|:-:|
|<a href="https://site-7q12wp5fs.hackclub.dev/winter"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/FEFyWVET55Kx-5sxyyj_fBprfZoD7ctiqavDrROzvptsvmFVqgndjgeNV0XXb25rFgF-loLH0A5MF9XqzotddA.png&w=600" alt="Screenshot of /winter" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/z_ApejN__E9xpXWulfFi0E5lHxRMSLp8PXsH4PNdiqrEEWULuqH8ZNmkuM-672PlZpEBjFvLy1H5VEZ78BsxlA.png">(view full size)</a> |







Commit 4cc0862d6e7df87057d7802ecf73ee03be62c410 (https://site-7q12wp5fs.hackclub.dev).

2022-12-18 00:48 UTC, exu3 requested changes
Thanks for adding this! Some feedback:

The copy feels a bit long.
I don't think it should be all-italicized.

Thoughts on something like this that touches the footer?
<img width="1145" alt="Screenshot 2022-12-17 at 7 46 55 PM" src="https://user-images.githubusercontent.com/72365100/208271805-4e409051-1173-4117-a978-46add758eacb.png">

Don't know how this would look, but maybe we could move the artist credit to the landing, and use a badge/pill like the homepage?

2022-12-18 02:44 UTC, bellesea commented
> Thanks for adding this! Some feedback:
> 
> The copy feels a bit long. I don't think it should be all-italicized.
> 
> Thoughts on something like this that touches the footer? <img alt="Screenshot 2022-12-17 at 7 46 55 PM" width="1145" src="https://user-images.githubusercontent.com/72365100/208271805-4e409051-1173-4117-a978-46add758eacb.png">
> 
> Don't know how this would look, but maybe we could move the artist credit to the landing, and use a badge/pill like the homepage?

oooo love this!!

2022-12-18 19:43 UTC, exu3 approved these changes

2022-12-18 19:43 UTC, merged