Change background image to Outernet, Add Jams & change the hackathons to recent ones
hackclub/site pull request #877
Opened 2023-08-24 15:30 UTC by tregsthedev

- Changes the background to Outernet Image
- Add jams notice to the workshops section
- Changed Hackathons to have HackOC & LeLand Hacks

2023-08-24 15:32 UTC, sampoder requested changes
Looks great! However, I propose we keep the Assemble background to distinguish `/clubs` from `/`

2023-08-24 15:37 UTC, sampoder commented on pages/clubs.js
> +            like the{' '}
It might be worthwhile finding hackathons that have a post-hackathon recap site / newspaper article on them or working with Ian & Robert / Maggie to make something like that for Leland Hacks & HackOC. I think we want to give people a sense of what hackathons are like. I seem to remember there being a HackOC documentary somewhere, maybe we could link that?

cc: @robert-goll @maggie-j-liu @YodaLightsabr

2023-08-24 15:38 UTC, sampoder commented on pages/clubs.js
> +                worth!) and 18 <a href="https://jams.hackclub.com"> Jams </a>{' '}
```suggestion
                worth!) and 18 <a href="https://jams.hackclub.com">Jams</a>{' '}
```

2023-08-24 18:19 UTC, robert-goll commented
[Hack OC mini-doc](https://youtu.be/Hs-hMMeHXaY)
Ian and I are going to meet Sunday and we've been planning on writing a recap if that's of interest as well

2023-08-24 18:48 UTC, sampoder commented
Oh that's awesome! Thoughts on linking the mini-doc @robert-goll @tregsthedev?

2023-08-24 19:01 UTC, tregsthedev commented
The Mini doc works! I'll change the url

2023-08-24 19:11 UTC, sampoder commented
I guess my question is more: do you think it accurately represents what the
event was like? Does it communicate what we want to communicate about
hackathons? It's been a while since I watched it so I wanted to get others'
thoughts


On Thu, Aug 24, 2023 at 12:01 PM Arav Narula ***@***.***>
wrote:

> The Mini doc works! I'll change the url
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/site/pull/877#issuecomment-1692252654>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJP3VRAGG7NFHEYACZSWHZLXW6QHZANCNFSM6AAAAAA35GWQDU>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-08-24 19:17 UTC, sampoder commented
I just watched the video myself, I think I'd say it does that pretty well through the interviews so I'd be cool with linking it. Others: thoughts?

2023-08-27 18:17 UTC, tregsthedev commented
The video captures HackOC really well, & it shows some of the work that went into the interviews & the overall feel of the hackathon. If Robert & Ian are okay with linking to it, then let's add it!

2023-08-27 20:27 UTC, robert-goll commented
It's good with me!

2023-09-01 23:46 UTC, tregsthedev commented on pages/clubs.js
> +            like the{' '}
cc @maggie-j-liu

2023-09-02 18:12 UTC, tregsthedev commented
Is there any other hackathons we can feature by club leaders or hack clubbers where they have a recap or documentary?

2023-09-02 18:42 UTC, sampoder commented
LCH has a recap page of sorts: https://lioncityhacks.com/. I think CarolinaHacks has a documentary.

2023-12-02 21:32 UTC, sampoder reviewed
quick changes, then merging

2023-12-02 21:32 UTC, sampoder commented on pages/clubs.js
> +import OuternetImgFile from '../public/home/outernet-110.jpg'
```suggestion
```

2023-12-02 21:32 UTC, sampoder commented on pages/clubs.js
> +        gradient="linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5))"
```suggestion
        src={AssembleImgFile}
        alt="Hack Clubbers assemble at Figma HQ for the first IRL hackathon in SF since 2020: Assemble. 📸 Photo by Kunal Botla, Hack Clubber in MA!"
        priority
```

2023-12-02 21:32 UTC, sampoder commented on pages/clubs.js
> +          Hackers at Outernet in VT
```suggestion
          Hackers at Assemble in SF
```

2023-12-02 21:32 UTC, sampoder commented on pages/clubs.js
> +            like the{' '}
```suggestion
            like <a href="https://lioncityhacks.com">Lion City Hacks</a> &{' '}
            <a href="https://www.youtube.com/watch?v=Hs-hMMeHXaY">HackOC</a>, take part in year long
            programs like <NextLink href="/onboard">OnBoard</NextLink>, and compete in events
            like the{' '}
```

2023-12-02 21:33 UTC, sampoder commented on pages/clubs.js
> +        pt: [5, 5],
```suggestion
        pt: [5, 6],
```

2023-12-02 21:33 UTC, merged

2023-12-02 21:53 UTC, tregsthedev commented
Curios, what did you change? Also totally forgot about this PR, sorry!

2023-12-02 22:19 UTC, aramshiva commented
> * Changes the background to Outernet Image
> * Add jams notice to the workshops section
> * Changed Hackathons to have HackOC & LeLand Hacks

@tregsthedev

2023-12-02 23:04 UTC, tregsthedev commented
Those are my original changes