Redesign of the newsletter section!
hackclub/site pull request #955
Opened 2023-10-11 15:56 UTC by developedbytoby

2023-10-11 17:21 UTC, grymmy requested changes
It seems to me that there are a large number of changes in this PR relating to formatting that do not relate to the actual redesign that was the cause for the PR in the first place.  Can these formatting changes be done as a separate diff to clearly delineate where the feature begins/ends vs the other changes to ;'s, "'s, and whitespace?

2023-10-13 16:22 UTC, developedbytoby commented
Hey @grymmy! Just removed the formatting.

2023-10-13 19:59 UTC, grymmy approved these changes
Lgtm @maxwofford I believe you were gonna do a design pass

2023-10-13 20:46 UTC, developedbytoby commented
@maxwofford have also fixed corner radius + padding issues!

2023-10-25 15:44 UTC, maxwofford approved these changes
Added a couple small styling comments, but overall this is approved for merge!

2023-10-25 15:44 UTC, maxwofford commented on components/index/cards/mailing-list.js
> +import Icon from "@hackclub/icons";
Did you mean to switch this to single quote, semicolon lines?

2023-10-25 15:44 UTC, maxwofford commented on components/mail-card.js
> +              <Box>
Lots of nesting in this area-- are all these `<Box>`s needed?

2023-10-25 15:44 UTC, maxwofford commented on components/index/cards/mailing-list.js
> +import { format } from "date-fns";
Most of our pages list local files imports below npm imports

2023-10-25 21:50 UTC, maxwofford commented
Awesome! Go for merge

2023-10-25 21:53 UTC, merged